# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_spare_part_not_from_store.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback
from settings import VERSION
from PyQt5 import QtCore, QtGui, QtWidgets
from db import service_session, check_if_consumable_exist_on_service, Consumables


class Ui_Add_Spare_Part_Not_From_Store(QtWidgets.QWidget):
    window_closed = QtCore.pyqtSignal()  # Το Signal πρεπει να είναι εκτός __init__ δεν δουλευει αλλιως

    def __init__(self, *args, **kwargs):
        super(Ui_Add_Spare_Part_Not_From_Store, self).__init__(*args, **kwargs)
        self.selected_table = None
        self.data_to_show = None
        self.selected_service_id = None
        self.selected_calendar_id = None
        self.selected_machine = None
        self.selected_customer_id = None

        self.font_14_bold = QtGui.QFont()
        self.font_14_bold.setFamily("Calibri")
        self.font_14_bold.setPointSize(14)
        self.font_14_bold.setBold(True)
        self.font_14_bold.setWeight(75)

        self.font_12 = QtGui.QFont()
        self.font_12.setFamily("Calibri")
        self.font_12.setPointSize(12)
        self.font_12.setBold(False)
        self.font_12.setWeight(75)

        self.font_12_bold = QtGui.QFont()
        self.font_12_bold.setFamily("Calibri")
        self.font_12_bold.setPointSize(12)
        self.font_12_bold.setBold(True)
        self.font_12_bold.setWeight(75)

        self.font_13 = QtGui.QFont()
        self.font_13.setFamily("Calibri")
        self.font_13.setPointSize(13)
        self.font_13.setBold(False)
        self.font_13.setWeight(75)

        self.font_13_bold = QtGui.QFont()
        self.font_13_bold.setFamily("Calibri")
        self.font_13_bold.setPointSize(13)
        self.font_13_bold.setBold(True)
        self.font_13_bold.setWeight(75)

    def setupUi(self, Add_Spare_Part_Not_From_Store):
        Add_Spare_Part_Not_From_Store.setObjectName("Form")
        Add_Spare_Part_Not_From_Store.resize(508, 448)
        self.gridLayout = QtWidgets.QGridLayout(Add_Spare_Part_Not_From_Store)
        self.gridLayout.setObjectName("gridLayout")

        self.top_label = QtWidgets.QLabel(Add_Spare_Part_Not_From_Store)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_label.sizePolicy().hasHeightForWidth())
        self.top_label.setSizePolicy(sizePolicy)
        self.top_label.setMinimumSize(QtCore.QSize(0, 30))
        self.top_label.setFont(self.font_14_bold)
        self.top_label.setStyleSheet("background-color: rgb(0, 85, 127);\n"
                                     "color: rgb(255, 255, 255);")
        self.top_label.setAlignment(QtCore.Qt.AlignCenter)
        self.top_label.setObjectName("top_label")
        self.gridLayout.addWidget(self.top_label, 0, 0, 1, 3)

        self.code_label = QtWidgets.QLabel(Add_Spare_Part_Not_From_Store)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.code_label.sizePolicy().hasHeightForWidth())
        self.code_label.setSizePolicy(sizePolicy)
        self.code_label.setMinimumSize(QtCore.QSize(0, 30))
        self.code_label.setFont(self.font_12_bold)
        self.code_label.setStyleSheet("background-color: rgb(255, 170, 0); color: rgb(255, 255, 255);")
        self.code_label.setAlignment(QtCore.Qt.AlignCenter)
        self.code_label.setObjectName("code_label")
        self.gridLayout.addWidget(self.code_label, 1, 0, 1, 1)
        self.code_lineEdit = QtWidgets.QLineEdit(Add_Spare_Part_Not_From_Store)
        self.code_lineEdit.setMinimumSize(QtCore.QSize(350, 35))
        self.code_lineEdit.setFont(self.font_13)
        self.code_lineEdit.setObjectName("code_lineEdit")
        self.gridLayout.addWidget(self.code_lineEdit, 1, 1, 1, 2)

        self.description_label = QtWidgets.QLabel(Add_Spare_Part_Not_From_Store)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description_label.sizePolicy().hasHeightForWidth())
        self.description_label.setSizePolicy(sizePolicy)
        self.description_label.setMinimumSize(QtCore.QSize(0, 30))
        self.description_label.setFont(self.font_12_bold)
        self.description_label.setStyleSheet("background-color: rgb(93, 93, 93); color: rgb(255, 255, 255);")
        self.description_label.setAlignment(QtCore.Qt.AlignCenter)
        self.description_label.setObjectName("description_label")
        self.gridLayout.addWidget(self.description_label, 2, 0, 1, 1)
        self.description_lineEdit = QtWidgets.QLineEdit(Add_Spare_Part_Not_From_Store)
        self.description_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.description_lineEdit.setFont(self.font_13)
        self.description_lineEdit.setObjectName("description_lineEdit")
        self.gridLayout.addWidget(self.description_lineEdit, 2, 1, 1, 2)

        self.pieces_label = QtWidgets.QLabel(Add_Spare_Part_Not_From_Store)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pieces_label.sizePolicy().hasHeightForWidth())
        self.pieces_label.setSizePolicy(sizePolicy)
        self.pieces_label.setMinimumSize(QtCore.QSize(0, 30))
        self.pieces_label.setFont(self.font_12_bold)
        self.pieces_label.setStyleSheet("background-color: rgb(93, 93, 93); color: rgb(255, 255, 255);")
        self.pieces_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pieces_label.setObjectName("pieces_label")
        self.gridLayout.addWidget(self.pieces_label, 3, 0, 1, 1)
        self.pieces_lineEdit = QtWidgets.QLineEdit(Add_Spare_Part_Not_From_Store)
        self.pieces_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.pieces_lineEdit.setFont(self.font_13)
        self.pieces_lineEdit.setObjectName("pieces_lineEdit")
        self.gridLayout.addWidget(self.pieces_lineEdit, 3, 1, 1, 2)

        self.part_no_label = QtWidgets.QLabel(Add_Spare_Part_Not_From_Store)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.part_no_label.sizePolicy().hasHeightForWidth())
        self.part_no_label.setSizePolicy(sizePolicy)
        self.part_no_label.setMinimumSize(QtCore.QSize(0, 30))
        self.part_no_label.setFont(self.font_12_bold)
        self.part_no_label.setStyleSheet("background-color: rgb(0, 85, 127); color: rgb(255, 255, 255);")
        self.part_no_label.setAlignment(QtCore.Qt.AlignCenter)
        self.part_no_label.setObjectName("part_no_label")
        self.gridLayout.addWidget(self.part_no_label, 5, 0, 1, 1)
        self.part_no_lineEdit = QtWidgets.QLineEdit(Add_Spare_Part_Not_From_Store)
        self.part_no_lineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.part_no_lineEdit.setFont(self.font_13)
        self.part_no_lineEdit.setObjectName("part_no_lineEdit")
        self.gridLayout.addWidget(self.part_no_lineEdit, 5, 1, 1, 2)

        self.notes_label = QtWidgets.QLabel(Add_Spare_Part_Not_From_Store)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.notes_label.sizePolicy().hasHeightForWidth())
        self.notes_label.setSizePolicy(sizePolicy)
        self.notes_label.setMinimumSize(QtCore.QSize(0, 30))
        self.notes_label.setFont(self.font_12_bold)
        self.notes_label.setStyleSheet("background-color: rgb(93, 93, 93); color: rgb(255, 255, 255);")
        self.notes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.notes_label.setObjectName("notes_label")
        self.gridLayout.addWidget(self.notes_label, 7, 0, 1, 3)
        self.notes_textEdit = QtWidgets.QTextEdit(Add_Spare_Part_Not_From_Store)
        self.notes_textEdit.setFont(self.font_13)
        self.notes_textEdit.setObjectName("notes_textEdit")
        self.gridLayout.addWidget(self.notes_textEdit, 8, 0, 1, 3)

        self.save_toolButton = QtWidgets.QToolButton(Add_Spare_Part_Not_From_Store)
        self.save_toolButton.setFont(self.font_12_bold)
        self.save_toolButton.setStyleSheet("background-color: rgb(103, 103, 103); color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_toolButton.setIcon(icon)
        self.save_toolButton.setIconSize(QtCore.QSize(30, 30))
        self.save_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.save_toolButton.setObjectName("save_toolButton")
        self.save_toolButton.clicked.connect(self.add_spare_part_to_db)
        self.gridLayout.addWidget(self.save_toolButton, 9, 0, 1, 2)

        self.retranslateUi(Add_Spare_Part_Not_From_Store)
        QtCore.QMetaObject.connectSlotsByName(Add_Spare_Part_Not_From_Store)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Add_Spare_Part_Not_From_Store", f"Προσθήκη ανταλλακτικού εκτός αποθήκης {VERSION}"))
        self.pieces_label.setText(_translate("Add_Spare_Part_Not_From_Store", "Τεμάχια"))
        self.top_label.setText(_translate("Add_Spare_Part_Not_From_Store", "Προσθήκη ανταλλακτικού"))
        self.description_label.setText(_translate("Add_Spare_Part_Not_From_Store", "Περιγραφή"))
        self.code_label.setText(_translate("Add_Spare_Part_Not_From_Store", "Κωδικός"))
        self.part_no_label.setText(_translate("Add_Spare_Part_Not_From_Store", "Part No"))
        self.notes_label.setText(_translate("Add_Spare_Part_Not_From_Store", "Σημειώσεις"))
        self.save_toolButton.setText(_translate("Add_Spare_Part_Not_From_Store", "Αποθήκευση"))

    def add_spare_part_to_db(self):
        given_code = self.code_lineEdit.text().replace(" ", "")
        if given_code == "":
            self.code_lineEdit.setStyleSheet("background-color: red; color: white;")
        else:
            if check_if_consumable_exist_on_service(given_code, self.selected_service_id):
                QtWidgets.QMessageBox.critical(None, "Σφάλμα!", f"Ο κωδικός {given_code} υπάρχει")
                self.code_lineEdit.setStyleSheet("background-color: red; color: white;")
                return
            else:
                self.code_lineEdit.setStyleSheet("background-color: green; color: white;")
                try:
                    new_consumable = Consumables(PARTS_NR=self.part_no_lineEdit.text(),
                                                 ΠΕΡΙΓΡΑΦΗ=self.description_lineEdit.text(),
                                                 ΚΩΔΙΚΟΣ=self.code_lineEdit.text(),
                                                 ΤΕΜΑΧΙΑ=self.pieces_lineEdit.text(),
                                                 ΠΑΡΑΤΗΡΗΣΗΣ=self.notes_textEdit.toPlainText(),
                                                 ΜΗΧΑΝΗΜΑ=self.selected_machine.Εταιρεία,
                                                 Service_ID=self.selected_service_id,
                                                 Customer_ID=self.selected_customer_id,
                                                 Calendar_ID=self.selected_calendar_id)
                    service_session.add(new_consumable)
                    service_session.commit()
                    answer = QtWidgets.QMessageBox.question(None, "Ερώτηση!", f"Θέλετε να προσθέσετε άλλο προιόν;",
                                                            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                                                            QtWidgets.QMessageBox.No)
                    if answer == QtWidgets.QMessageBox.Yes:
                        self.code_lineEdit.clear()
                        self.description_lineEdit.clear()
                        self.pieces_lineEdit.clear()
                        self.part_no_lineEdit.clear()
                        self.notes_textEdit.clear()
                        return
                    else:
                        self.close()
                except Exception:
                    traceback.print_exc()
                    QtWidgets.QMessageBox.critical(None, "Προσοχή!", f"Κάτι δεν πήγε καλά προιόν δεν αποθυκεύτηκε!")
                    return


    def closeEvent(self, event):
        self.window_closed.emit()
        event.accept()
        # event.ignore()  # if you want the window to never be closed


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    Add_Spare_Part_Not_From_Store = QtWidgets.QWidget()
    ui = Ui_Add_Spare_Part_Not_From_Store()
    ui.setupUi(Add_Spare_Part_Not_From_Store)
    Add_Spare_Part_Not_From_Store.show()
    sys.exit(app.exec_())
