# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enable_machine_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import traceback
import sqlalchemy
from db import service_session, Customer, get_customers_with_inactive_machines
from PyQt5 import QtCore, QtGui, QtWidgets
from settings import VERSION, root_logger

sys.stderr.write = root_logger.error
sys.stdout.write = root_logger.info


class Ui_enable_machine_window(QtWidgets.QTabWidget):
    window_closed = QtCore.pyqtSignal()

    def __init__(self):
        super(Ui_enable_machine_window, self).__init__()
        self.selected_customer = None
        self.selected_machine = None
        self.customer_machines = None
        self.customers_with_machines = get_customers_with_inactive_machines()  # Dict
        self.all_customers = [customer for customer in self.customers_with_machines.keys()]
        self.all_customers_names = [customer.Επωνυμία_Επιχείρησης for customer in self.all_customers]

    def setupUi(self, enable_machine_window):
        enable_machine_window.setObjectName("enable_machine_window")
        enable_machine_window.resize(612, 350)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/add_machine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        enable_machine_window.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(enable_machine_window)
        self.gridLayout.setObjectName("gridLayout")
        self.machiness_label = QtWidgets.QLabel(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.machiness_label.sizePolicy().hasHeightForWidth())
        self.machiness_label.setSizePolicy(sizePolicy)
        self.machiness_label.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.machiness_label.setFont(font)
        self.machiness_label.setStyleSheet("background-color: rgb(45, 45, 55);\n"
                                           "color: rgb(255, 255, 255);")
        self.machiness_label.setAlignment(QtCore.Qt.AlignCenter)
        self.machiness_label.setObjectName("machiness_label")
        self.gridLayout.addWidget(self.machiness_label, 1, 0, 1, 1)
        self.start_counter_label = QtWidgets.QLabel(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_counter_label.sizePolicy().hasHeightForWidth())
        self.start_counter_label.setSizePolicy(sizePolicy)
        self.start_counter_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_counter_label.setFont(font)
        self.start_counter_label.setObjectName("start_counter_label")
        self.gridLayout.addWidget(self.start_counter_label, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.serial_number_label = QtWidgets.QLabel(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_number_label.sizePolicy().hasHeightForWidth())
        self.serial_number_label.setSizePolicy(sizePolicy)
        self.serial_number_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.serial_number_label.setFont(font)
        self.serial_number_label.setObjectName("serial_number_label")
        self.gridLayout.addWidget(self.serial_number_label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.copiers_notes_textEdit = QtWidgets.QTextEdit(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copiers_notes_textEdit.sizePolicy().hasHeightForWidth())
        self.copiers_notes_textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.copiers_notes_textEdit.setFont(font)
        self.copiers_notes_textEdit.setObjectName("copiers_notes_textEdit")
        self.copiers_notes_textEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.copiers_notes_textEdit, 11, 0, 1, 2)
        self.customers_label = QtWidgets.QLabel(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.customers_label.sizePolicy().hasHeightForWidth())
        self.customers_label.setSizePolicy(sizePolicy)
        self.customers_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.customers_label.setFont(font)
        self.customers_label.setStyleSheet("color: rgb(255, 255, 255);\n"
                                           "background-color: rgb(255, 170, 0);")
        self.customers_label.setAlignment(QtCore.Qt.AlignCenter)
        self.customers_label.setObjectName("customers_label")
        self.gridLayout.addWidget(self.customers_label, 0, 0, 1, 1, )
        self.start_date_label = QtWidgets.QLabel(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_date_label.sizePolicy().hasHeightForWidth())
        self.start_date_label.setSizePolicy(sizePolicy)
        self.start_date_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.start_date_label.setFont(font)
        self.start_date_label.setObjectName("start_date_label")
        self.gridLayout.addWidget(self.start_date_label, 5, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.started_date_dateEdit = QtWidgets.QDateEdit(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.started_date_dateEdit.sizePolicy().hasHeightForWidth())
        self.started_date_dateEdit.setSizePolicy(sizePolicy)
        self.started_date_dateEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.started_date_dateEdit.setFont(font)
        self.started_date_dateEdit.setCalendarPopup(True)
        self.started_date_dateEdit.setObjectName("started_date_dateEdit")
        self.started_date_dateEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.started_date_dateEdit, 6, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.copier_notes_label = QtWidgets.QLabel(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copier_notes_label.sizePolicy().hasHeightForWidth())
        self.copier_notes_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.copier_notes_label.setFont(font)
        self.copier_notes_label.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.copier_notes_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.copier_notes_label.setStyleSheet("background-color: rgb(89, 89, 89);\n"
                                              "color: rgb(255, 255, 255);")
        self.copier_notes_label.setLocale(QtCore.QLocale(QtCore.QLocale.Greek, QtCore.QLocale.Greece))
        self.copier_notes_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.copier_notes_label.setAlignment(QtCore.Qt.AlignCenter)
        self.copier_notes_label.setObjectName("copier_notes_label")
        self.gridLayout.addWidget(self.copier_notes_label, 10, 0, 1, 2)
        self.copier_model_lineEdit = QtWidgets.QLineEdit(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copier_model_lineEdit.sizePolicy().hasHeightForWidth())
        self.copier_model_lineEdit.setSizePolicy(sizePolicy)
        self.copier_model_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.copier_model_lineEdit.setFont(font)
        self.copier_model_lineEdit.setObjectName("copier_model_lineEdit")
        self.copier_model_lineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.copier_model_lineEdit, 3, 1, 1, 1)
        self.start_counter_lineEdit = QtWidgets.QLineEdit(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_counter_lineEdit.sizePolicy().hasHeightForWidth())
        self.start_counter_lineEdit.setSizePolicy(sizePolicy)
        self.start_counter_lineEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.start_counter_lineEdit.setFont(font)
        self.start_counter_lineEdit.setObjectName("start_counter_lineEdit")
        self.start_counter_lineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.start_counter_lineEdit, 6, 0, 1, 1)
        self.copier_model_label = QtWidgets.QLabel(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copier_model_label.sizePolicy().hasHeightForWidth())
        self.copier_model_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.copier_model_label.setFont(font)
        self.copier_model_label.setObjectName("copier_model_label")
        self.gridLayout.addWidget(self.copier_model_label, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.serial_number_lineEdit = QtWidgets.QLineEdit(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serial_number_lineEdit.sizePolicy().hasHeightForWidth())
        self.serial_number_lineEdit.setSizePolicy(sizePolicy)
        self.serial_number_lineEdit.setMaximumSize(QtCore.QSize(299, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.serial_number_lineEdit.setFont(font)
        self.serial_number_lineEdit.setObjectName("serial_number_lineEdit")
        self.serial_number_lineEdit.setReadOnly(True)
        self.gridLayout.addWidget(self.serial_number_lineEdit, 3, 0, 1, 1)

        # Πελάτης
        self.customers_comboΒox = QtWidgets.QComboBox(enable_machine_window)
        self.customers_comboΒox.setFont(font)
        self.customers_comboΒox.addItems(self.all_customers_names)
        self.customers_comboΒox.currentIndexChanged.connect(self.show_customer_machines)
        self.gridLayout.addWidget(self.customers_comboΒox, 0, 1, 1, 1)

        self.machines_comboΒox = QtWidgets.QComboBox(enable_machine_window)
        self.machines_comboΒox.setFont(font)
        self.machines_comboΒox.currentIndexChanged.connect(self.show_selected_machine_details)
        self.gridLayout.addWidget(self.machines_comboΒox, 1, 1, 1, 1)
        self.save_new_copier_toolButton = QtWidgets.QToolButton(enable_machine_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_new_copier_toolButton.sizePolicy().hasHeightForWidth())
        self.save_new_copier_toolButton.setSizePolicy(sizePolicy)
        self.save_new_copier_toolButton.setMinimumSize(QtCore.QSize(0, 30))
        self.save_new_copier_toolButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.save_new_copier_toolButton.setFont(font)
        self.save_new_copier_toolButton.setStyleSheet("background-color: rgb(104, 104, 104);\n"
                                                      "color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/Save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_new_copier_toolButton.setIcon(icon1)
        self.save_new_copier_toolButton.setIconSize(QtCore.QSize(40, 40))
        self.save_new_copier_toolButton.setShortcut("Ctrl+S")
        self.save_new_copier_toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.save_new_copier_toolButton.setAutoRaise(False)
        self.save_new_copier_toolButton.setObjectName("save_new_copier_toolButton")
        self.save_new_copier_toolButton.clicked.connect(self.enable_machine)
        self.gridLayout.addWidget(self.save_new_copier_toolButton, 12, 0, 1, 1, QtCore.Qt.AlignHCenter)

        # Συντομέυσεις
        # Esc
        self.shortcut_esc = QtWidgets.QShortcut(QtGui.QKeySequence('Escape'), enable_machine_window)
        self.shortcut_esc.activated.connect(lambda: self.close())

        self.retranslateUi(enable_machine_window)
        QtCore.QMetaObject.connectSlotsByName(enable_machine_window)

    def retranslateUi(self, enable_machine_window):
        _translate = QtCore.QCoreApplication.translate
        enable_machine_window.setWindowTitle(_translate("enable_machine_window", f"Ενεργοποιήση μηχανήματος {VERSION}"))
        self.machiness_label.setText(_translate("enable_machine_window", "Μηχανήματα"))
        self.start_counter_label.setText(_translate("enable_machine_window", "Μετρητής Εναρξης"))
        self.serial_number_label.setText(_translate("enable_machine_window", "Σειριακός αριθμός"))
        self.customers_label.setText(_translate("enable_machine_window", "Πελατολόγιο"))
        self.start_date_label.setText(_translate("enable_machine_window", "Ημηρομηνία  εναρξης"))
        self.copier_notes_label.setText(_translate("enable_machine_window", "Σημειώσεις"))
        self.copier_model_label.setText(_translate("enable_machine_window", "Εταιρεία - Μοντέλο"))
        self.save_new_copier_toolButton.setText(_translate("enable_machine_window", "  Αποθήκευση"))

    def show_customer_machines(self):
        selected_customer_index = self.customers_comboΒox.currentIndex()
        self.selected_customer = self.all_customers[selected_customer_index]

        self.machines_comboΒox.clear()
        try:
            self.customer_machines = self.customers_with_machines[self.selected_customer]
            self.selected_machine = self.customer_machines[0]
            self.machines_comboΒox.addItems([machine.Εταιρεία for machine in self.customer_machines])

            self.serial_number_lineEdit.setText(self.selected_machine.Serial)
            self.started_date_dateEdit.setDate(
                QtCore.QDate.fromString(self.selected_machine.Εναρξη, "dd'/'MM'/'yyyy"))
            self.start_counter_lineEdit.setText(self.selected_machine.Μετρητής_έναρξης)
            self.copier_model_lineEdit.setText(self.selected_machine.Εταιρεία)
            self.copiers_notes_textEdit.setText(self.selected_machine.Σημειώσεις)
        except (AttributeError, TypeError):
            pass

    def show_selected_machine_details(self):
        selected_machine_index = self.machines_comboΒox.currentIndex()
        self.selected_machine = self.customer_machines[selected_machine_index]
        self.serial_number_lineEdit.setText(self.selected_machine.Serial)
        self.started_date_dateEdit.setDate(QtCore.QDate.fromString(self.selected_machine.Εναρξη, "dd'/'MM'/'yyyy"))
        self.start_counter_lineEdit.setText(self.selected_machine.Μετρητής_έναρξης)
        self.copier_model_lineEdit.setText(self.selected_machine.Εταιρεία)
        self.copiers_notes_textEdit.setText(self.selected_machine.Σημειώσεις)

    def enable_machine(self):
        try:
            answer = QtWidgets.QMessageBox.question(None, "Προσοχή", "Σίγουρα θέλετε να ενεργοποιήσετε το μηχάνημα;",
                                           QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                                                        QtWidgets.QMessageBox.No)
            if answer == QtWidgets.QMessageBox.Yes:
                self.selected_machine.Κατάσταση = 1
                service_session.commit()
                QtWidgets.QMessageBox.information(None, "Πληροφορία", "Το μηχάνημα ενεργοποιήθηκε!")
                self.close()
        except Exception:
            print(traceback.print_exc())
            QtWidgets.QMessageBox.critical(None, "Σφάλμα", "Το μηχάνημα ΔΕΝ ενεργοποιήθηκε!")
            return

    def closeEvent(self, event):
        self.window_closed.emit()
        event.accept()
        # event.ignore()  # if you want the window to never be closed


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    app.setStyle("Fusion")
    enable_machine_window = QtWidgets.QWidget()
    ui = Ui_enable_machine_window()
    ui.setupUi(enable_machine_window)
    enable_machine_window.show()
    sys.exit(app.exec_())
